---
title: "S3 Summary"
author: "Huiding Chen"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: "hide"
---

```{r,include=FALSE}
library(knitr)
library(dplyr)
library(tidyverse)
library(cat)
library(survey)
library(kableExtra)
library(VGAM)
library(distributionsrd)
library(ggplot2)
library(truncnorm)
library(reshape2)
library(paletteer)
library(plotly)
library(stringr)
library(purrr)
library(RVAideMemoire)
library(glmnet)
library(DT)
knitr::opts_chunk$set(warning = FALSE,message = FALSE)
```


# Brief Summary


## Intro

```{r}
n = 1000

### Simulations
load("S3.RData")

```

## Report Function

```{r}
source("../../Functions/report_function.R")
source("../../Functions/apply_row_colors.R")
```

# Results with Linear Methods


```{r}

if(file.exists("../../Results/Res_methods/S3_summary.RData")){
  out <- readRDS("../../Results/Res_methods/S3_summary.RData")
}else{
  out <- fun.rep(x = sim_result,n = n)
  saveRDS(out, "../../Results/Res_methods/S3_summary.RData")
}

```

## Population Prevalence

```{r}
out_pop_mean <- as.data.frame(out$out_mean)
out_pop_mean <- out_pop_mean %>% t()
apply_row_colors(out_pop_mean,names_caption = "Population Prevalence",size = 1)
```


```{r}
out_pop_mean <- out_pop_mean %>%
  as.data.frame() %>%
  select(c(unweighted,trueweight,svy_oneway_rake,ps_oneway_raw,ps_oneway_rake,ps_vs_twoway_raw,ps_vs_twoway_rake,ps_vs_stepwise_twoway_rake))
out_pop_mean <- out_pop_mean[c("Relative Bias(Mean)","variance","Emp SD","NomCoverage","Oracle Coverage","Ratio of NAs"),]
out_pop_mean[1,] <- out_pop_mean[1,]*100
out_pop_mean[2,] <- out_pop_mean[2,]*1e5
out_pop_mean[3,] <- out_pop_mean[3,]*1e5
out_pop_mean[4,] <- out_pop_mean[4,]*100
out_pop_mean[5,] <- out_pop_mean[5,]*100
out_pop_mean[6,] <- out_pop_mean[6,]*100

apply_row_colors(out_pop_mean,names_caption = "Population Prevalence",size = 1)
```


## Elapsed Time

```{r}
out_time <- out$out_time
kable(out_time,format = "html",caption = "Elapsed Time (in seconds)",align = "c")%>%
  kable_styling(full_width = FALSE, c("striped", "condensed"),)
```

## Average Size

```{r}
out_size <- out$out_size
kable(out_size,format = "html",caption = "Average Size",align = "c")%>%
  kable_styling(full_width = FALSE, c("striped", "condensed"),)
sum(out_size)
```

## Average Variable Selected

```{r}
out_vs_n <- out$out_vs_n
out_vs_n_step <- out$out_vs_n_step
out_vs <- cbind(VS = out_vs_n,Step = out_vs_n_step)
kable(out_vs,format = "html",caption = "Average Variables Selected",align = "c")%>%
  kable_styling(full_width = FALSE, c("striped", "condensed"),)
```

## Boxplot

```{r}
tmp <- out$out_p
level_order <- out$out_level_order
p <- ggplot(data = tmp, aes(x=Method, y=value,fill=Method))+
    geom_violin()+
    geom_boxplot(outlier.colour="red")+
    ggtitle("Boxplot of Bias") + 
    xlab("Methods") +
    ylab("Bias") +
    geom_jitter(shape=16, position=position_jitter(0))+ 
    stat_summary(fun="mean", geom="point", shape=23, size=4,na.rm = TRUE)+
    stat_summary(fun="median", geom="point", shape=1, size=3,na.rm = TRUE)+
    geom_hline(yintercept=0, linetype="dashed", color = "red")+
    theme(legend.text = element_text(size=8),
          legend.position="bottom",axis.text.x=element_blank(),
          axis.ticks.x=element_blank()) + 
    guides(fill=guide_legend(nrow=6,byrow=TRUE)) + 
    scale_x_discrete(limits = level_order) 
ggplotly(p)
```


## Variance Correction

```{r}
out_varcor <- out$out_varcor
pos_count <- out$out_pos_count
mod_count <- out$out_mod_count

varcor_1 <- c(out_varcor[c(6,2,11)])
names(varcor_1)[3] <- "ratio_var"
varcor_2 <- c(out_varcor[c(7,3,10)])
varcor_3 <- c(out_varcor[c(12,11)])


varcor_cov_dt <- data.frame("NomCoverage" = varcor_3,
                            "OracleCoverage" = out$out_varcor_cov[c(3,1)])
rownames(varcor_cov_dt) <- c("Full","Original")

kable(varcor_cov_dt,format = "html",caption = "Variance Correction: Coverage",align = "c")%>%
  kable_styling(full_width = FALSE, c("striped", "condensed"))

```
